version: '3.1'

services:

  dev-db:
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-dev:
